function gmmPlot()
%CREATEFIGURE(Y1)
%  Y1:  vector of y data
%  age_scoresXXcv_15s_equalClasses_UBMzTrainTest.mat

Y1 = [0.4288, 0.5324, 0.5599, 0.5953, 0.6194, 0.6365, 0.6430, 0.6442, 0.6506, 0.6366];
%  Auto-generated by MATLAB on 08-Dec-2015 14:05:07

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'GMM16','GMM32','GMM64','GMM128','GMM256','GMM512','GMM1024','GMM2048','GMM4096','GMM8192'});
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot(Y1);

